abstract: Encode the value automatically using HTML::Entities
author: Hironori Yoshida  C<< <yoshida@cpan.org> >>
distribution_type: module
generated_by: Module::Install version 0.630
license: perl
name: Template-Stash-HTML-Entities
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::Entities: 0
  Template::Config: 0
  version: 0
version: 0.02
